---
__sshd_os_supported: true

__sshd_service: ssh
__sshd_packages:
  - openssh-server
  - openssh-sftp-server
# Ubuntu 22.04 finally ships with drop-in directory support so we touch
# just included file with highest priority by default
__sshd_config_file: /etc/ssh/sshd_config.d/00-ansible_system_role.conf
__sshd_config_mode: "0644"
# the defaults here represent the defaults shipped in the main sshd_config
__sshd_defaults:
  Include: /etc/ssh/sshd_config.d/*.conf
  KbdInteractiveAuthentication: false
  UsePAM: true
  PasswordAuthentication: true
  PermitRootLogin: false
  AcceptEnv: LANG LC_*
  Subsystem: "sftp  /usr/lib/openssh/sftp-server"
  Ciphers: "aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com"
  KexAlgorithms: "diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha256,curve25519-sha256,curve25519-sha256@libssh.org"
  HostKeyAlgorithms: "ssh-ed25519,rsa-sha2-256,rsa-sha2-512"
  MACs: "hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha2-512-etm@openssh.com,umac-128-etm@openssh.com"

__sshd_runtime_directory: /run/sshd

__sshd_drop_in_dir_mode: '0755'
__sshd_main_config_file: /etc/ssh/sshd_config
