---
__sshd_service: ssh
__sshd_packages:
  - openssh-server
  - openssh-sftp-server
__sshd_config_mode: "0644"
__sshd_defaults:
  ChallengeResponseAuthentication: false
  UsePAM: true
  PermitRootLogin: false
  PasswordAuthentication: true
  X11Forwarding: true
  PrintMotd: false
  AcceptEnv: LANG LC_*
  Subsystem: "sftp  /usr/lib/openssh/sftp-server"
  Ciphers: "aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com"
  KexAlgorithms: "diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha256,curve25519-sha256,curve25519-sha256@libssh.org"
  HostKeyAlgorithms: "ssh-ed25519,rsa-sha2-256,rsa-sha2-512"
  MACs: "hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha2-512-etm@openssh.com,umac-128-etm@openssh.com"

__sshd_os_supported: true
__sshd_runtime_directory: /run/sshd
