---
repos:
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.27.1
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$
        types: [file, yaml]
        entry: yamllint --strict
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v6.5.2
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
